# Generated by Django 5.1.4 on 2025-01-07 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitors_id', models.IntegerField()),
                ('employee_id', models.IntegerField()),
                ('date', models.CharField(max_length=200)),
                ('time', models.CharField(max_length=200)),
                ('visitors_type', models.CharField(blank=True, max_length=200, null=True)),
                ('detail', models.TextField(blank=True, null=True)),
                ('purpose', models.TextField()),
                ('visitors_timing', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('employee_approval', models.CharField(max_length=200, null=True)),
                ('check_in_time', models.CharField(max_length=200)),
                ('check_out_time', models.CharField(max_length=200)),
                ('created_by', models.IntegerField()),
                ('created_at', models.CharField(max_length=200)),
                ('updated_at', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Appointment',
                'db_table': 'appointment',
            },
        ),
        migrations.CreateModel(
            name='appointment_reject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_id', models.IntegerField()),
                ('reason', models.CharField(max_length=999)),
                ('date', models.CharField(max_length=200)),
                ('time', models.CharField(max_length=200)),
                ('created_at', models.CharField(max_length=200)),
                ('updated_at', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'appointment_reject',
                'db_table': 'appointment_reject',
            },
        ),
        migrations.CreateModel(
            name='areas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_code', models.CharField(max_length=10)),
                ('area_name', models.CharField(max_length=100)),
                ('location_id', models.IntegerField()),
                ('created_at', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'areas',
                'db_table': 'areas',
            },
        ),
        migrations.CreateModel(
            name='auto_email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField()),
                ('created_at', models.CharField(max_length=200)),
                ('updated_at', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'auto_email',
                'db_table': 'auto_email',
            },
        ),
        migrations.CreateModel(
            name='cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('state_id', models.IntegerField()),
            ],
            options={
                'verbose_name': 'cities',
                'db_table': 'cities',
            },
        ),
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_code', models.CharField(max_length=599)),
                ('company_name', models.CharField(max_length=100)),
                ('location_id', models.IntegerField()),
                ('address_1', models.TextField()),
                ('address_2', models.TextField()),
                ('pincode', models.CharField(max_length=15)),
                ('status', models.IntegerField()),
                ('created_at', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'company',
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortname', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=150)),
                ('phonecode', models.IntegerField()),
            ],
            options={
                'verbose_name': 'countries',
                'db_table': 'countries',
            },
        ),
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=255)),
                ('department_code', models.CharField(max_length=50)),
                ('department_color_code', models.CharField(max_length=50)),
                ('company_id', models.IntegerField()),
                ('location_id', models.IntegerField()),
                ('created_at', models.CharField(max_length=200)),
                ('updated_at', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'department',
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('allow_check_in', models.BooleanField()),
                ('created_at', models.CharField(max_length=200)),
                ('updated_at', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'designation',
                'db_table': 'designation',
            },
        ),
        migrations.CreateModel(
            name='gate_pass_no',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_id', models.IntegerField()),
                ('gate_pass_number', models.IntegerField()),
                ('created_at', models.CharField(max_length=200)),
                ('updated_at', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'gate_pass_no',
                'db_table': 'gate_pass_no',
            },
        ),
        migrations.CreateModel(
            name='location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_id', models.IntegerField()),
                ('state_id', models.IntegerField()),
                ('city_id', models.IntegerField()),
                ('location_name', models.CharField(max_length=200)),
                ('status', models.IntegerField()),
                ('created_at', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'location',
                'db_table': 'location',
            },
        ),
        migrations.CreateModel(
            name='roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'roles',
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='safety_training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('video_file', models.FileField(upload_to='safety_training')),
                ('is_active', models.BooleanField()),
                ('created_at', models.CharField(max_length=200)),
                ('updated_at', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'safety_training',
                'db_table': 'safety_training',
            },
        ),
        migrations.CreateModel(
            name='states',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('country_id', models.IntegerField()),
            ],
            options={
                'verbose_name': 'states',
                'db_table': 'states',
            },
        ),
        migrations.CreateModel(
            name='visitors_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_id', models.IntegerField()),
                ('start_time', models.CharField(max_length=200)),
                ('stop_time', models.CharField(max_length=200)),
                ('created_at', models.CharField(max_length=200)),
                ('updated_at', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'visitors_log',
                'db_table': 'visitors_log',
            },
        ),
        migrations.CreateModel(
            name='website_setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/website_setting/logo')),
                ('favicon', models.ImageField(upload_to='static/website_setting/favicon')),
                ('website_name', models.CharField(max_length=200)),
                ('website_link', models.CharField(max_length=200)),
                ('copyright', models.CharField(max_length=999)),
                ('smtp_host', models.CharField(max_length=200)),
                ('smtp_user', models.CharField(max_length=200)),
                ('smtp_password', models.CharField(max_length=200)),
                ('from_name', models.CharField(max_length=200)),
                ('from_email', models.CharField(max_length=200)),
                ('whatsapp_notification', models.BooleanField()),
                ('created_at', models.CharField(max_length=200)),
                ('updated_at', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'website_setting',
                'db_table': 'website_setting',
            },
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(default=None, max_length=599, null=True)),
                ('mobile', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('is_active', models.BooleanField(default=1)),
                ('confirmed', models.BooleanField(default=0)),
                ('type', models.CharField(max_length=200)),
                ('uni_id', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='user')),
                ('company_id', models.IntegerField()),
                ('department_id', models.IntegerField()),
                ('designation_id', models.IntegerField()),
                ('location_id', models.IntegerField()),
                ('created_by', models.IntegerField()),
                ('employee_code', models.IntegerField()),
                ('created_at', models.CharField(max_length=200)),
                ('updated_at', models.CharField(max_length=200)),
                ('document', models.FileField(blank=True, null=True, upload_to='user/document')),
                ('groups', models.ManyToManyField(blank=True, related_name='custom_user_set', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='custom_user_set_permissions', to='auth.permission')),
            ],
            options={
                'verbose_name': 'User',
                'db_table': 'users',
            },
        ),
    ]
