# Generated by Django 5.1.4 on 2025-01-10 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_safety_training',
            field=models.BooleanField(default=False),
        ),
    ]
