# Generated by Django 5.0.7 on 2024-07-19 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors_app', '0004_rename_name_user_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default=1, upload_to='http://127.0.0.1:8000/visitor_management/static/user/'),
            preserve_default=False,
        ),
    ]
