# Generated by Django 5.0.7 on 2024-07-24 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors_app', '0007_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='purpose',
            field=models.TextField(default=1, max_length=599),
            preserve_default=False,
        ),
    ]
