# Generated by Django 5.0.7 on 2024-07-25 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors_app', '0009_alter_appointment_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='detail',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='visitors_type',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='document',
            field=models.FileField(default=1, upload_to='user/document'),
            preserve_default=False,
        ),
    ]
