# Generated by Django 5.0.7 on 2024-07-25 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors_app', '0011_alter_user_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='visitors_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
