# Generated by Django 5.0.7 on 2024-07-26 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors_app', '0016_cities'),
    ]

    operations = [
        migrations.CreateModel(
            name='location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_id', models.IntegerField()),
                ('state_id', models.IntegerField()),
                ('city_id', models.IntegerField()),
                ('location_name', models.CharField(max_length=200)),
                ('status', models.IntegerField()),
                ('created_at', models.CharField(max_length=200)),
            ],
        ),
    ]
