# Generated by Django 5.0.7 on 2024-07-26 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitors_app', '0017_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'location'},
        ),
        migrations.AlterModelTable(
            name='location',
            table='location',
        ),
    ]
