# Generated by Django 5.0.7 on 2024-07-26 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors_app', '0018_alter_location_options_alter_location_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='areas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_code', models.CharField(max_length=10)),
                ('area_name', models.CharField(max_length=100)),
                ('location_id', models.IntegerField()),
                ('created_at', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'areas',
                'db_table': 'areas',
            },
        ),
    ]
