# Generated by Django 5.0.7 on 2024-07-26 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors_app', '0019_areas'),
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_code', models.CharField(max_length=20)),
                ('company_name', models.CharField(max_length=100)),
                ('location_id', models.IntegerField()),
                ('address_1', models.TextField()),
                ('address_2', models.TextField()),
                ('pincode', models.CharField(max_length=15)),
                ('status', models.IntegerField()),
                ('created_at', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'company',
                'db_table': 'company',
            },
        ),
    ]
