# Generated by Django 5.0.7 on 2024-07-29 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors_app', '0020_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=255)),
                ('department_code', models.CharField(max_length=50)),
                ('company_id', models.IntegerField()),
                ('location_id', models.IntegerField()),
                ('created_at', models.CharField(max_length=200)),
                ('updated_at', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'department',
                'db_table': 'department',
            },
        ),
    ]
