# Generated by Django 5.0.7 on 2024-07-29 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors_app', '0021_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='area_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='company_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='department_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='location_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
