# Generated by Django 5.0.7 on 2024-07-30 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors_app', '0022_user_area_id_user_company_id_user_department_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='area_id',
            field=models.TextField(),
        ),
    ]
