# Generated by Django 5.0.7 on 2024-07-31 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors_app', '0024_alter_company_company_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointment_reject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_id', models.IntegerField()),
                ('reason', models.CharField(max_length=999)),
                ('date', models.CharField(max_length=200)),
                ('time', models.CharField(max_length=200)),
                ('created_at', models.CharField(max_length=200)),
                ('updated_at', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'appointment_reject',
                'db_table': 'appointment_reject',
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='area_id',
        ),
    ]
