# Generated by Django 5.0.7 on 2024-08-01 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors_app', '0025_appointment_reject_remove_user_area_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='visitors_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_id', models.IntegerField()),
                ('start_time', models.CharField(max_length=200)),
                ('stop_time', models.CharField(max_length=200)),
                ('created_at', models.CharField(max_length=200)),
                ('updated_at', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'visitors_log',
                'db_table': 'visitors_log',
            },
        ),
    ]
