# Generated by Django 5.0.7 on 2024-08-02 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors_app', '0026_visitors_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='check_in_time',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='check_out_time',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
