# Generated by Django 5.0.7 on 2024-08-08 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors_app', '0028_appointment_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_by',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
