# Generated by Django 5.0.7 on 2024-08-21 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors_app', '0031_appointment_access_area_appointment_access_card_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='access_card_id',
            field=models.IntegerField(max_length=200),
        ),
    ]
