# Generated by Django 5.1.4 on 2025-01-07 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors_app', '0033_remove_appointment_access_area_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='auto_email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField()),
                ('created_at', models.CharField(max_length=200)),
                ('updated_at', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'auto_email',
                'db_table': 'auto_email',
            },
        ),
        migrations.CreateModel(
            name='designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('allow_check_in', models.BooleanField()),
                ('created_at', models.CharField(max_length=200)),
                ('updated_at', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'designation',
                'db_table': 'designation',
            },
        ),
        migrations.CreateModel(
            name='gate_pass_no',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_id', models.IntegerField()),
                ('gate_pass_number', models.IntegerField()),
                ('created_at', models.CharField(max_length=200)),
                ('updated_at', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'gate_pass_no',
                'db_table': 'gate_pass_no',
            },
        ),
        migrations.CreateModel(
            name='website_setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/website_setting/logo')),
                ('favicon', models.ImageField(upload_to='static/website_setting/favicon')),
                ('website_name', models.CharField(max_length=200)),
                ('website_link', models.CharField(max_length=200)),
                ('copyright', models.CharField(max_length=999)),
                ('smtp_host', models.CharField(max_length=200)),
                ('smtp_user', models.CharField(max_length=200)),
                ('smtp_password', models.CharField(max_length=200)),
                ('from_name', models.CharField(max_length=200)),
                ('from_email', models.CharField(max_length=200)),
                ('whatsapp_notification', models.BooleanField()),
                ('created_at', models.CharField(max_length=200)),
                ('updated_at', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'website_setting',
                'db_table': 'website_setting',
            },
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='access_card_id',
            new_name='visitors_timing',
        ),
        migrations.AddField(
            model_name='appointment',
            name='employee_approval',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='department_color_code',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='designation_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
