# Generated by Django 5.1.4 on 2025-01-07 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors_app', '0034_auto_email_designation_gate_pass_no_website_setting_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='safety_training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('video_file', models.FileField(upload_to='safety_training')),
                ('is_active', models.BooleanField()),
                ('created_at', models.CharField(max_length=200)),
                ('updated_at', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'safety_training',
                'db_table': 'safety_training',
            },
        ),
    ]
