# Generated by Django 5.1.4 on 2025-01-07 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors_app', '0035_safety_training'),
    ]

    operations = [
        migrations.AlterField(
            model_name='safety_training',
            name='video_file',
            field=models.FileField(upload_to='safety_training/'),
        ),
    ]
