# Generated by Django 5.0.7 on 2024-07-17 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(default=None, max_length=599, null=True)),
                ('facebook_id', models.CharField(default=None, max_length=599, null=True)),
                ('google_id', models.CharField(default=None, max_length=599, null=True)),
                ('apple_user_id', models.CharField(default=None, max_length=599, null=True)),
                ('mobile', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('dob', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('website', models.URLField()),
                ('brief', models.TextField()),
                ('is_admin', models.BooleanField(default=0)),
                ('is_active', models.BooleanField(default=1)),
                ('confirmed', models.BooleanField(default=0)),
                ('confirmation_code', models.CharField(max_length=599)),
                ('remember_token', models.CharField(max_length=599)),
                ('created_at', models.CharField(max_length=200)),
                ('updated_at', models.CharField(max_length=200)),
                ('groups', models.ManyToManyField(blank=True, related_name='custom_user_set', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='custom_user_set_permissions', to='auth.permission')),
            ],
            options={
                'verbose_name': 'User',
                'db_table': 'users',
            },
        ),
    ]
