# Generated by Django 5.0.7 on 2024-07-17 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitors_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
